version: '2'

services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../data/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_PASSWORD: root

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
